departamentos:
    path:  /
    defaults: { _controller: "BackendBundle:Departamentos:index" }

departamentos_show:
    path:  /{id}/show
    defaults: { _controller: "BackendBundle:Departamentos:show" }

departamentos_new:
    path:  /new
    defaults: { _controller: "BackendBundle:Departamentos:new" }

departamentos_create:
    path:  /create
    defaults: { _controller: "BackendBundle:Departamentos:create" }
    requirements: { _method: post }

departamentos_edit:
    path:  /{id}/edit
    defaults: { _controller: "BackendBundle:Departamentos:edit" }

departamentos_update:
    path:  /{id}/update
    defaults: { _controller: "BackendBundle:Departamentos:update" }
    requirements: { _method: post|put }

departamentos_delete:
    path:  /{id}/delete
    defaults: { _controller: "BackendBundle:Departamentos:delete" }
    requirements: { _method: post|delete }
    
departamentos_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "BackendBundle:Departamentos:deleteById" }
    requirements: { _method: get }
    

departamentos_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "BackendBundle:Departamentos:bulk" }
    requirements: { _method: post }
    
