empresa:
    path:  /
    defaults: { _controller: "BackendBundle:Empresa:index" }

empresa_show:
    path:  /{id}/show
    defaults: { _controller: "BackendBundle:Empresa:show" }

empresa_new:
    path:  /new
    defaults: { _controller: "BackendBundle:Empresa:new" }

empresa_create:
    path:  /create
    defaults: { _controller: "BackendBundle:Empresa:create" }
    requirements: { _method: post }

empresa_edit:
    path:  /{id}/edit
    defaults: { _controller: "BackendBundle:Empresa:edit" }

empresa_update:
    path:  /{id}/update
    defaults: { _controller: "BackendBundle:Empresa:update" }
    requirements: { _method: post|put }

empresa_delete:
    path:  /{id}/delete
    defaults: { _controller: "BackendBundle:Empresa:delete" }
    requirements: { _method: post|delete }
    
empresa_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "BackendBundle:Empresa:deleteById" }
    requirements: { _method: get }
    

empresa_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "BackendBundle:Empresa:bulk" }
    requirements: { _method: post }
    
