rrhh:
    path:  /
    defaults: { _controller: "BackendBundle:Rrhh:index" }

rrhh_show:
    path:  /{id}/show
    defaults: { _controller: "BackendBundle:Rrhh:show" }

rrhh_new:
    path:  /new
    defaults: { _controller: "BackendBundle:Rrhh:new" }

rrhh_create:
    path:  /create
    defaults: { _controller: "BackendBundle:Rrhh:create" }
    requirements: { _method: post }

rrhh_edit:
    path:  /{id}/edit
    defaults: { _controller: "BackendBundle:Rrhh:edit" }

rrhh_update:
    path:  /{id}/update
    defaults: { _controller: "BackendBundle:Rrhh:update" }
    requirements: { _method: post|put }

rrhh_delete:
    path:  /{id}/delete
    defaults: { _controller: "BackendBundle:Rrhh:delete" }
    requirements: { _method: post|delete }
    
rrhh_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "BackendBundle:Rrhh:deleteById" }
    requirements: { _method: get }
    

rrhh_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "BackendBundle:Rrhh:bulk" }
    requirements: { _method: post }
    
