notificaciones:
    path:  /
    defaults: { _controller: "NotificacionesBundle:Notificaciones:index" }

notificaciones_show:
    path:  /{id}/show
    defaults: { _controller: "NotificacionesBundle:Notificaciones:show" }

notificaciones_new:
    path:  /new
    defaults: { _controller: "NotificacionesBundle:Notificaciones:new" }

notificaciones_create:
    path:  /create
    defaults: { _controller: "NotificacionesBundle:Notificaciones:create" }
    requirements: { _method: post }

notificaciones_edit:
    path:  /{id}/edit
    defaults: { _controller: "NotificacionesBundle:Notificaciones:edit" }

notificaciones_update:
    path:  /{id}/update
    defaults: { _controller: "NotificacionesBundle:Notificaciones:update" }
    requirements: { _method: post|put }

notificaciones_delete:
    path:  /{id}/delete
    defaults: { _controller: "NotificacionesBundle:Notificaciones:delete" }
    requirements: { _method: post|delete }
    
notificaciones_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "NotificacionesBundle:Notificaciones:deleteById" }
    requirements: { _method: get }
    

notificaciones_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "NotificacionesBundle:Notificaciones:bulk" }
    requirements: { _method: post }
    
