BackendBundle\Entity\Autorizaciones:
    type: entity
    table: autorizaciones
    indexes:
        fk_autorizaciones_solicitudes1_idx:
            columns:
                - solicitud
        fk_autorizaciones_usuario1_idx:
            columns:
                - autorizado_por
        fk_autorizaciones_ordenescompra1_idx:
            columns:
                - ordenescompra_id
        fk_autorizaciones_config1_idx:
            columns:
                - estado_autorizacion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fechaAutorizacion:
            type: datetime
            nullable: true
            column: fecha_autorizacion
        comentario:
            type: string
            nullable: true
            length: 450
            options:
                fixed: false
    manyToOne:
        estadoAutorizacion:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estado_autorizacion:
                    referencedColumnName: id
            orphanRemoval: false
        ordenescompra:
            targetEntity: Ordenescompra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ordenescompra_id:
                    referencedColumnName: id
            orphanRemoval: false
        solicitud:
            targetEntity: Solicitudes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                solicitud:
                    referencedColumnName: id
            orphanRemoval: false
        autorizadoPor:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                autorizado_por:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
