BackendBundle\Entity\Campana:
    type: entity
    table: campana
    indexes:
        fk_campana_proveedores_clientes1_idx:
            columns:
                - proveedores_clientes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        fechaFacturacion:
            type: datetime
            nullable: true
            column: fecha_facturacion
        fechaInicio:
            type: datetime
            nullable: true
            column: fecha_inicio
        fechaTermino:
            type: datetime
            nullable: true
            column: fecha_termino
    manyToOne:
        proveedoresClientes:
            targetEntity: ProveedoresClientes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                proveedores_clientes:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
