BackendBundle\Entity\Documentos:
    type: entity
    table: documentos
    indexes:
        fk_documentos_config_idx:
            columns:
                - tipo_documento
        fk_documentos_empresa1_idx:
            columns:
                - empresa
        fk_documentos_rrhh1_idx:
            columns:
                - rrhh
        fk_documentos_usuario1_idx:
            columns:
                - cargado_por
        fk_documentos_facturas1_idx:
            columns:
                - facturas
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        archivo:
            type: string
            nullable: true
            length: 450
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        fechaCarga:
            type: datetime
            nullable: true
            column: fecha_carga
    manyToOne:
        tipoDocumento:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_documento:
                    referencedColumnName: id
            orphanRemoval: false
        empresa:
            targetEntity: Empresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empresa:
                    referencedColumnName: id
            orphanRemoval: false
        facturas:
            targetEntity: Facturas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                facturas:
                    referencedColumnName: id
            orphanRemoval: false
        rrhh:
            targetEntity: Rrhh
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rrhh:
                    referencedColumnName: id
            orphanRemoval: false
        cargadoPor:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cargado_por:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
