BackendBundle\Entity\Inventario:
    type: entity
    table: inventario
    indexes:
        fk_inventario_empresa1_idx:
            columns:
                - empresa
        fk_inventario_config1_idx:
            columns:
                - estado
    uniqueConstraints:
        codigo_UNIQUE:
            columns:
                - codigo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreProducto:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: nombre_producto
        descripcion:
            type: string
            nullable: true
            length: 450
            options:
                fixed: false
        cantidad:
            type: float
            nullable: true
            precision: 10
            scale: 0
        codigo:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        estado:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estado:
                    referencedColumnName: id
            orphanRemoval: false
        empresa:
            targetEntity: Empresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empresa:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
