BackendBundle\Entity\ItemPresupuesto:
    type: entity
    table: item_presupuesto
    indexes:
        fk_item_preupuesto_presupuesto1_idx:
            columns:
                - presupuesto
        fk_item_preupuesto_config1_idx:
            columns:
                - tipo_ingreso_gasto
        fk_item_preupuesto_campana1_idx:
            columns:
                - campana
        fk_item_preupuesto_config2_idx:
            columns:
                - item_gasto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        valor:
            type: float
            nullable: true
            precision: 10
            scale: 0
        descripcion:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        duracionMeses:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: duracion_meses
        mesInicio:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: mes_inicio
        anoInicio:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: ano_inicio
        prorateable:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        presupuesto:
            targetEntity: Presupuesto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                presupuesto:
                    referencedColumnName: id
            orphanRemoval: false
        tipoIngresoGasto:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_ingreso_gasto:
                    referencedColumnName: id
            orphanRemoval: false
        campana:
            targetEntity: Campana
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                campana:
                    referencedColumnName: id
            orphanRemoval: false
        itemGasto:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                item_gasto:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
