BackendBundle\Entity\Menu:
    type: entity
    table: menu
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        link:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
