BackendBundle\Entity\Presupuesto:
    type: entity
    table: presupuesto
    indexes:
        fk_presupuesto_empresa1_idx:
            columns:
                - empresa
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fechaIngreso:
            type: datetime
            nullable: true
            column: fecha_ingreso
        valor:
            type: float
            nullable: true
            precision: 10
            scale: 0
        fechaPago:
            type: datetime
            nullable: true
            column: fecha_pago
        item:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        comentario:
            type: string
            nullable: true
            length: 450
            options:
                fixed: false
    manyToOne:
        empresa:
            targetEntity: Empresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                empresa:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
