BackendBundle\Entity\Registropago:
    type: entity
    table: registropago
    indexes:
        fk_registropago_facturas1_idx:
            columns:
                - factura
        fk_registropago_config1_idx:
            columns:
                - forma_pago
        fk_registropago_config2_idx:
            columns:
                - tipooperacion
        fk_registropago_tarjeta_credito1_idx:
            columns:
                - tarjeta_credito
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
        fechaPago:
            type: datetime
            nullable: true
            column: fecha_pago
        codigoOperacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: codigo_operacion
    manyToOne:
        tarjetaCredito:
            targetEntity: TarjetaCredito
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tarjeta_credito:
                    referencedColumnName: id
            orphanRemoval: false
        formaPago:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                forma_pago:
                    referencedColumnName: id
            orphanRemoval: false
        tipooperacion:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipooperacion:
                    referencedColumnName: id
            orphanRemoval: false
        factura:
            targetEntity: Facturas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                factura:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
