BackendBundle\Entity\TarjetaCredito:
    type: entity
    table: tarjeta_credito
    indexes:
        fk_tarjeta_credito_banco1_idx:
            columns:
                - banco
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numeroTarjetaCredito:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: numero_tarjeta_credito
    manyToOne:
        banco:
            targetEntity: Banco
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                banco:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
