itemsoc:
    path:  /{id}
    defaults: { _controller: "FinanzasBundle:ItemsOc:index",id:null }
    methods: [get|post]

itemsoc_show:
    path:  /{id}/show
    defaults: { _controller: "FinanzasBundle:ItemsOc:show" }

itemsoc_new:
    path:  /new/{id}
    defaults: { _controller: "FinanzasBundle:ItemsOc:new",id:null }
    methods: [get|post]

itemsoc_create:
    path:  /create
    defaults: { _controller: "FinanzasBundle:ItemsOc:create" }
    requirements: { _method: post }

itemsoc_edit:
    path:  /{id}/edit
    defaults: { _controller: "FinanzasBundle:ItemsOc:edit" }

itemsoc_update:
    path:  /{id}/update
    defaults: { _controller: "FinanzasBundle:ItemsOc:update" }
    requirements: { _method: post|put }

itemsoc_delete:
    path:  /{id}/delete
    defaults: { _controller: "FinanzasBundle:ItemsOc:delete" }
    requirements: { _method: post|delete }
    
itemsoc_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "FinanzasBundle:ItemsOc:deleteById" }
    requirements: { _method: get }
    

itemsoc_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "FinanzasBundle:ItemsOc:bulk" }
    requirements: { _method: post }
    
