backend_empresa:
    resource: "@EmpresaBundle/Resources/config/routing/empresa.yml"
    prefix:   /
backend_departamentos:
    resource: "@EmpresaBundle/Resources/config/routing/departamentos.yml"
    prefix:   /