backend_facturas:
    resource: "@BackendBundle/Resources/config/routing/facturas.yml"
    prefix:   /facturas











backend_homepage:
    path:     /
    defaults: { _controller: LoginBundle:Login:index }
