backend_departamentos:
    resource: "@BackendBundle/Resources/config/routing/departamentos.yml"
    prefix:   /departamentos







backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
