backend_autorizaciones:
    resource: "@BackendBundle/Resources/config/routing/autorizaciones.yml"
    prefix:   /autorizaciones




backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
