backend_usuario:
    resource: "@BackendBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario





backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
