backend_itemsoc:
    resource: "@BackendBundle/Resources/config/routing/itemsoc.yml"
    prefix:   /itemsoc


backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
